"""game_id foreign key added to choices

Revision ID: f99fdaa8ae1c
Revises: a4cdc336ab21
Create Date: 2023-10-09 18:29:51.952998

"""
import sqlalchemy as sa
from alembic import op
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f99fdaa8ae1c"
down_revision: Union[str, None] = "a4cdc336ab21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("choices", sa.Column("game_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "choices", "games", ["game_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "choices", type_="foreignkey")
    op.drop_column("choices", "game_id")
    # ### end Alembic commands ###
