"""is_active modified

Revision ID: efc44391b689
Revises: f99fdaa8ae1c
Create Date: 2023-10-10 21:04:52.144460

"""
import sqlalchemy as sa
from alembic import op
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "efc44391b689"
down_revision: Union[str, None] = "f99fdaa8ae1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("choices", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("games", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("scenes", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenes", "is_active")
    op.drop_column("games", "is_active")
    op.drop_column("choices", "is_active")
    # ### end Alembic commands ###
