"""scene_title_created

Revision ID: e26be6b5e713
Revises: b15a77597397
Create Date: 2023-10-06 14:07:19.299703

"""
import sqlalchemy as sa
from alembic import op
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e26be6b5e713"
down_revision: Union[str, None] = "b15a77597397"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "choices", ["id"])
    op.create_unique_constraint(None, "games", ["id"])
    op.add_column("scenes", sa.Column("scene_title", sa.String(), nullable=True))
    op.create_unique_constraint(None, "scenes", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scenes", type_="unique")
    op.drop_column("scenes", "scene_title")
    op.drop_constraint(None, "games", type_="unique")
    op.drop_constraint(None, "choices", type_="unique")
    # ### end Alembic commands ###
